<?php

/**
 * @file
 * Truncate Tooltip module.
 */

/**
 * Implements hook_menu().
 */
function trunc_tooltip_menu() {
	$items = array();

	$items['admin/config/user-interface/trunc-tooltip'] = array(
		'title' => 'Tuncate Tooltip',
		'description' => 'Modify selectors used by module',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('trunc_tooltip_admin_settings'),
		'access arguments' => array('trunc_tooltip admin'),
		'file' => 'trunc_tooltip.admin.inc',
		'type' => MENU_NORMAL_ITEM
	);
	return $items;
}

/**
 * Implements template_preprocess_page
 */
function trunc_tooltip_preprocess_page(&$variables) {
	$base_path = drupal_get_path('module', 'trunc_tooltip');
	
	drupal_add_css($base_path . '/styles/trunc_tooltip.css');
	drupal_add_js(
		array(
			'trunc_tooltip' => array(
				'selectors' => variable_get('trunc_selectors', t('.field-name-title a, .rc-core-item-name a'))
			)
		),
		array('type' => 'setting')
	);
	drupal_add_js($base_path . '/js/trunc_tooltip.js', array('scope' => 'footer'));
}

/**
 * Implements hook_block_info().
 */
function trunc_tooltip_block_info() {
	$blocks = array();
	$blocks['trunc_tooltip_config'] = array(
		'info' => 'Truncate Tooltip Configuration',
		'cache' => DRUPAL_CACHE_GLOBAL
	);
	return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function trunc_tooltip_block_configure($delta = '') {
	$form = array();

	if($delta === 'trunc_tooltip_config') {
		$form['trunc_selectors'] = array(
			'#type' => 'textarea',
			'#title' => 'Field Selectors',
			'#description' => 'Enter selectors for truncated text field, separated by coma',
			'#default_value' => variable_get('trunc_selectors', t('.field-name-title a, .rc-core-item-name a'))
		);
	}
	return $form;
}

/**
 * Implements hook_block_save().
 */
function trunc_tooltip_block_save($delta = '', $edit = array()) {
	if($delta === 'trunc_tooltip_config') {
		variable_set('trunc_selectors', $edit['trunc_selectors']);

		drupal_add_js(
			array(
				'trunc_tooltip' => array(
					'selectors' => variable_get('trunc_selectors', t('.field-name-title a, .rc-core-item-name a'))
				)
			),
			array('type' => 'setting')
		);
	}
}