<?php

/**
 * @file
 * Truncate Tooltip module.
 */

/**
 * Implements hook_menu().
 */
function trunc_tooltip_menu() {
	$items = array();

	$items['admin/config/user-interface/trunc-tooltip'] = array(
		'title' => 'Tuncate Tooltip',
		'description' => 'Modify selectors used by module',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('trunc_tooltip_admin_settings'),
		'access arguments' => array('trunc_tooltip admin'),
		'file' => 'trunc_tooltip.admin.inc',
		'type' => MENU_NORMAL_ITEM
	);
	return $items;
}

/**
 * Implements hook_libraries_info().
 */
function trunc_tooltip_libraries_info() {
	$libraries = array();

	$libraries['trunc_tooltip_assets'] = array(
		'name' => 'Truncate Tooltip Assets',
		'vendor url' => 'http://bluetent.com',
		'version' => '1.0',
    'library path' => drupal_get_path('module', 'trunc_tooltip'),
		'files' => array(
			'js' => array(
				'js/trunc_tooltip.js'
			),
			'css' => array(
				'styles/trunc_tooltip.css'
			)
		)
	);
	return $libraries;
}

/**
 * Implements hook_page_alter().
 */
function trunc_tooltip_page_alter(&$page) {

  libraries_load('trunc_tooltip_assets');

	$page['content']['#attached']['js'][] = array(
		'type' => 'setting',
		'data' => array(
			'trunc_tooltip' => array(
				'selectors' => variable_get('trunc_selectors', t('.field-name-title a, .rc-core-item-name a'))
			)
		)
	);
}